### ISSUE TITLE
document the problem you were having

### ISSUE THREAD

**Issue by mgelbart** [Anmol6/DNGO-BO#4]
@Anmol6 in this issue thread, or somewhere else that we can find, please document the troubles you had with minibatch SGD. Include relevant links to SO, etc. and explain how you solved the problem.

**Comment by Anmol6** [comment]
Three main issues:
1) Optimization does not work with respect to placeholders, since they are not of the type tf.Variable. This can be overcome by creating a duplicate Variable that takes on the value of the placeholder and optimization with respect to this duplicate can then be done.
2) Another problem emerged when trying to solve 1. the `tf.assign()` function is an "operator" and thus must be called *everytime* the placeholder is fed a value -- ie. specifying an operation in a script is not enough. This was a good reminder to not make assumptions about how dynamic Tensorflow is. 

Helpful links for 1 and 2:
http://stackoverflow.com/questions/40647769/using-a-placeholder-as-a-tensorflow-variable-getting-error
http://stackoverflow.com/questions/40495631/convert-scalar-function-to-a-tensorflow-variable

3) There was a lot of casting to different data types (eg. `tf.float32` to `tf.float64` etc.) involved. Not much of a problem since the error messages told me where exactly the problem was, but a hassle nonetheless.
